name: slack

on:
  push:
    branches:
      - 'release/v[0-9]+\.[0-9]+'
      #1.The pipeline should be triggered whenever this is a push to a branch name with the following pattern release/v<digit>.<digit>

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
    
      
      
      #2.Scan the branch and generate report
      #3.Find vulnerabilities
      - name: Run Trivy vulnerability scanner in fs mode
        id: trivy
        uses: aquasecurity/trivy-action@0.19.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          #exit-code: '1'
          severity: 'CRITICAL'
          output: 'output.txt'
          ignore-unfixed: true
          vuln-type: 'os,library'

  
      
  
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          #SLACK_CHANNEL: general
          #SLACK_COLOR: '#ff00ff' # or a specific color like 'good' or '#ff00ff'
          #SLACK_ICON: https://github.com/rtCamp.png?size=48
          #SLACK_MESSAGE: 'Post Content :rocket:'
          #SLACK_TITLE: Post Title
          #SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    


    
        
        
      # Add other steps for your CI/CD pipeline...
